feat(dockerfile): bump base image to 3.17 + tor to 0.4.7.13-r0
Ilshidur/tor-relay-docker pull request #16
Opened 2023-02-01 14:58 UTC by tsjk

2023-02-01 14:58 UTC, tsjk commented
I'm using this, and it works.

2023-02-01 18:50 UTC, Ilshidur requested changes
Hello @tsjk.
Thank you very much for your contribution, I appreciate your interest in this project.

This looks good to me. Would you mind just changing the `RUN` line to this, please ?
 `RUN apk --no-cache add bash tzdata tor=0.4.7.13-r0`

I found out that `apk add --no-cache` has the same behavior than `apk update` in the beginning and `rm -rf /var/cache/apk/*` in the end (the `/etc/apk/cache` did not exist in the container).

2023-02-02 06:11 UTC, tsjk commented
Done

2023-03-03 18:28 UTC, Ilshidur approved these changes

2023-03-03 18:28 UTC, merged